title: 潘柏信
subtitle: 个人站
description: 欢迎来到我的个人站~
avatarTitle: leopardpan
avatarDesc: iOS / 机器学习
url: ''
enableToc: true
comment:
  disqus: leopard
social:
  weibo: 5366874726
  github: leopardpan
  jianshu: 2ada30d8d0f7
  mail: leopardpan@icloud.com
baidu:
  id: 8ba1c6be0953b6f9c2ba38e57f615421
ga:
  id: UA-84134159-3
  host: auto
permalink: '/:year/:month/:title/'
highlighter: rouge
textColor: null
cover_color: clear
blog_button:
  title: 博客主页
nav:
  - title: 所有文章
    description: archive
    url: /archive
  - title: 标签
    description: tags
    url: /tags
  - title: 技术支持
    description: support
    url: /support
  - title: 关于我
    description: about
    url: /about
gems:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 20
paginate_path: 'page/:num/'
baseurl: ''
